name: Corona notify

on:
  push
  # schedule:
  #  cron: '0 1 * * '

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: satackey/action-js-inline@v0.0.3
        with:
          script: |
            const {get} = require('https')
            const url ='https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_Landkreisdaten/FeatureServer/0/query?outFields=*&returnGeometry=false&resultOffset=0&resultRecordCount=10&f=json&orderByFields=cases7_per_100k%20desc&where=1%3D1&inSR=4326&geometry=%7B%22spatialReference%22%3A%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D%2C%22xmin%22%3A1149751.0163160919%2C%22ymin%22%3A6080183.255423946%2C%22xmax%22%3A1215563.29766954%2C%22ymax%22%3A6093559.735373834%7D&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects'

            get(url, res => {
              let body = ''
              res.on('data', d => body += d.toString())
              res.on('end', () => {
                const obj = JSON.parse(body)
                const { attributes } = obj.features.filter(({ attributes: { GEN } }) => GEN === 'Kaufbeuren')[1]
                console.log(attributes.cases7_per_100k)
              })
            })
